# Generated by Django 5.2.15 on 2026-08-14 12:03
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("djadyen", "0001_initial"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="adyenpaymentoption",
            name="guid",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal reference for this payment option",
                max_length=36,
                verbose_name="GUID",
            ),
        ),
    ]
