name: "Testing"

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    tests:
        name: Run the Django test suite
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.7", "3.8", "3.9", "3.10"]
                django-versions:
                    [
                        "pip install django==1.11",
                        "pip install django==2.0",
                        "pip install django==2.1",
                        "pip install django==2.2",
                        "pip install django==3.0",
                        "pip install django==3.1",
                        "pip install django==3.2",
                        "pip install django==4.0",
                    ]
        services:
            postgres:
                image: postgis/postgis:10-2.5
                env:
                    POSTGRES_HOST_AUTH_METHOD: trust
                ports:
                    - 5432:5432
                # needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Django
              run: ${{ matrix.django-version }}

            - name: Install dependencies
              run: |
                  pip install codecov django_webtest factory-boy psycopg2 pytest pytest-cov pytest-django pytest-pep8 pytest-pylint pytest-pythonpath pytest-runner requests-mock freezegun

            - name: Run tests
              run: |
                  py.test --cov-report=xml --cov=djadyen --verbose --junit-xml=junit.xml --color=yes tests

            - uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
