name: "Testing"

on:
    push:
        branches:
            - master
        tags:
            - "*"
    pull_request:
    workflow_dispatch:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - django-version: "3.2"
                      python-version: "3.9"
                    - django-version: "3.2"
                      python-version: "3.10"
                    - django-version: "3.2"
                      python-version: "3.11"
                    - django-version: "4.2"
                      python-version: "3.10"
                    - django-version: "4.2"
                      python-version: "3.11"
                    - django-version: "4.2"
                      python-version: "3.12"
                    - django-version: "5.2"
                      python-version: "3.11"
                    - django-version: "5.2"
                      python-version: "3.12"

        name: Run the test suite (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: pip install tox tox-gh-actions codecov

            - name: Run tests
              run: |
                  export TOXENV=py${PYTHON_VERSION/./}-django${DJANGO/./}
                  tox
                  codecov -e TOXENV,DJANGO --file reports/coverage-${TOXENV}.xml
              env:
                  PYTHON_VERSION: ${{ matrix.python-version }}
                  DJANGO: ${{ matrix.django-version }}

            - name: Publish coverage report
              uses: codecov/codecov-action@v1

    publish:
        name: Publish package to PyPI
        runs-on: ubuntu-latest
        needs: tests

        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.11"

            - name: Build sdist and wheel
              run: |
                  pip install pip setuptools wheel --upgrade
                  python setup.py sdist bdist_wheel
            - name: Publish a Python distribution to PyPI
              uses: pypa/gh-action-pypi-publish@v1.13.0
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_TOKEN }}
