name: "Testing"

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    tests:
        name: Run the Django test suite
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgis/postgis:10-2.5
                env:
                    POSTGRES_HOST_AUTH_METHOD: trust
                ports:
                    - 5432:5432
                # needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
                with:
                    python-version: "3.9"

            - run: |
                pip install tox codecov

            - run: |
                tox

            - uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
