name: "Testing"

on:
    push:
        branches:
            - main
        tags:
            - "*"
    pull_request:
    workflow_dispatch:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - django-version: "1.11.0"
                      python-version: "3.5"
                    - django-version: "1.11.0"
                      python-version: "3.6"
                    - django-version: "1.11.0"
                      python-version: "3.7"
                    # # Django 2.0
                    # - django-version: "2.0.0"
                    #   python-version: "3.5"
                    # - django-version: "2.0.0"
                    #   python-version: "3.6"
                    # - django-version: "2.0.0"
                    #   python-version: "3.7"
                    # # Django 2.1
                    # - django-version: "2.1.0"
                    #   python-version: "3.5"
                    # - django-version: "2.1.0"
                    #   python-version: "3.6"
                    # - django-version: "2.1.0"
                    #   python-version: "3.7"
                    # # Django 2.2
                    # - django-version: "2.2.0"
                    #   python-version: "3.5"
                    # - django-version: "2.2.0"
                    #   python-version: "3.6"
                    # - django-version: "2.2.0"
                    #   python-version: "3.7"
                    # - django-version: "2.2.0"
                    #   python-version: "3.8"
                    # - django-version: "2.2.0"
                    #   python-version: "3.9"
                    # # Django 3.0
                    # - django-version: "3.0.0"
                    #   python-version: "3.6"
                    # - django-version: "3.0.0"
                    #   python-version: "3.7"
                    # - django-version: "3.0.0"
                    #   python-version: "3.8"
                    # - django-version: "3.0.0"
                    #   python-version: "3.9"
                    # # Django 3.1
                    # - django-version: "3.1.0"
                    #   python-version: "3.6"
                    # - django-version: "3.1.0"
                    #   python-version: "3.7"
                    # - django-version: "3.1.0"
                    #   python-version: "3.8"
                    # - django-version: "3.1.0"
                    #   python-version: "3.9"
                    # # Django 3.2
                    # - django-version: "3.2.0"
                    #   python-version: "3.6"
                    # - django-version: "3.2.0"
                    #   python-version: "3.7"
                    # - django-version: "3.2.0"
                    #   python-version: "3.8"
                    # - django-version: "3.2.0"
                    #   python-version: "3.9"
                    # - django-version: "3.2.0"
                    #   python-version: "3.10"
                    # # Django 4.0
                    # - django-version: "4.0.0"
                    #   python-version: "3.8"
                    # - django-version: "4.0.0"
                    #   python-version: "3.9"
                    # - django-version: "4.0.0"
                    #   python-version: "3.10"
        name: Run the test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }})
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install dependencies
              run: pip install tox tox-gh-actions codecov

            - name: Run tests
              run: |
                  export TOXENV=py${PYTHON_VERSION/./}-django${DJANGO/./}
                  tox
                  codecov -e TOXENV,DJANGO --file reports/coverage-${TOXENV}.xml
              env:
                  PYTHON_VERSION: ${{ matrix.python }}
                  DJANGO: ${{ matrix.django }}

            - name: Publish coverage report
              uses: codecov/codecov-action@v1

    publish:
        name: Publish package to PyPI
        runs-on: ubuntu-latest
        needs: tests

        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9"

            - name: Build sdist and wheel
              run: |
                  pip install pip setuptools wheel --upgrade
                  python setup.py sdist bdist_wheel
            - name: Publish a Python distribution to PyPI
              uses: pypa/gh-action-pypi-publish@v1.4.1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_TOKEN }}
